### ISSUE TITLE
check 

### ISSUE THREAD

**Issue by azouzen** [Mrakovic-ORG/iCloud_Bypass#1]
-bash-3.2# ./BlackMagic $a:/usr/libexec/mobileactivationd   
i have use manuel method on mac  hang on this line i have change BlackMagic to 755 permit
but hang on thanks

**Comment by 0x11DFE** [comment]
Sorry i didn't understand, you had to give BlackMagic file permission 755 to make it work?

**Comment by azouzen** [comment]
Azous-MacBook-Air:~ azou$ scp -P 2222 /Users/azou/Downloads/iCloud_Bypass-master-2/BlackMagic root@127.0.0.1://usr/libexec/
The authenticity of host '[127.0.0.1]:2222 ([127.0.0.1]:2222)' can't be established.
RSA key fingerprint is SHA256:rilj/1IO5zQnJ27ag1bg8/U+wIun5bDpRlwxm/uy4VI.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known hosts.
root@127.0.0.1's password: 
BlackMagic                                                                             100% 2110KB   6.3MB/s   00:00    
Azous-MacBook-Air:~ azou$ 

i have copy the file to     /usr/libexec/           after 
Azous-MacBook-Air:~ azou$ ssh root@localhost -p 2222
The authenticity of host '[localhost]:2222 ([127.0.0.1]:2222)' can't be established.
RSA key fingerprint is SHA256:rilj/1IO5zQnJ27ag1bg8/U+wIun5bDpRlwxm/uy4VI.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[localhost]:2222' (RSA) to the list of known hosts.
root@localhost's password: 
-bash-3.2# mount -o rw,union,update /
<mobileactivationd /usr/libexec/mobileactivationdbak                         
-bash-3.2# cd /usr/libexec/                                                    
and now 
-bash-3.2# chmod 755 BlackMagic
-bash-3.2# ./BlackMagic
after this nothing stop work .....

**Comment by 0x11DFE** [comment]
You did not follow the bash script correctly, You must rename `BlackMagic `to `mobileactivationd` then give it permission 755 then reloading `/System/Library/LaunchDaemons/com.apple.mobileactivationd.plist`

**Comment by azouzen** [comment]
ok i tray it 
and for network ??? what ca i do ?

**Comment by azouzen** [comment]
````_
````
